"use client";

import { cn } from "@/lib/utils";
import { AlertTriangle, CheckCircle2, Clock, Zap } from "lucide-react";
import type { ActionPreview } from "@/lib/api-types";

interface ActionPreviewCardProps {
  action: ActionPreview;
  onApprove?: () => void;
  isApproving?: boolean;
  className?: string;
}

export function ActionPreviewCard({
  action,
  onApprove,
  isApproving = false,
  className,
}: ActionPreviewCardProps) {
  const isApproved = action.status === "APPROVED";

  return (
    <div className={cn("surface-card overflow-hidden", className)}>
      {/* Header */}
      <div className="px-5 py-4 border-b border-[#1e2130] flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-7 h-7 rounded bg-[#0a1528] border border-[#1d3a6e] flex items-center justify-center">
            <Zap className="w-3.5 h-3.5 text-[#3b82f6]" />
          </div>
          <div>
            <p className="text-sm font-semibold text-[#e8eaf6]">
              {action.title}
            </p>
            <p className="text-xs font-mono text-[#5a6380] mt-0.5 tracking-wider uppercase">
              {action.action_type}
            </p>
          </div>
        </div>

        {/* Draft badge */}
        {!isApproved && (
          <div className="flex items-center gap-1.5 px-3 py-1 bg-[#1a1500] border border-[#78350f] rounded text-xs font-bold text-[#f59e0b] tracking-widest uppercase">
            <Clock className="w-3 h-3" />
            DRAFT — PENDING APPROVAL
          </div>
        )}
        {isApproved && (
          <div className="flex items-center gap-1.5 px-3 py-1 bg-[#052e16] border border-[#14532d] rounded text-xs font-bold text-[#22c55e] tracking-widest uppercase">
            <CheckCircle2 className="w-3 h-3" />
            APPROVED
          </div>
        )}
      </div>

      {/* Explanation */}
      <div className="px-5 py-4 border-b border-[#1e2130]">
        <p className="text-xs uppercase tracking-widest text-[#5a6380] font-medium mb-2">
          Recommendation
        </p>
        <p className="text-sm text-[#9ba3bf] leading-relaxed">
          {action.explanation}
        </p>
      </div>

      {/* Draft content preview */}
      <div className="px-5 py-4 border-b border-[#1e2130]">
        <div className="flex items-center gap-2 mb-3">
          <p className="text-xs uppercase tracking-widest text-[#5a6380] font-medium">
            Generated Action Preview
          </p>
          <div className="flex-1 h-px bg-[#1e2130]" />
        </div>
        <pre className="text-xs font-mono text-[#9ba3bf] bg-[#141520] border border-[#1e2130] rounded p-4 whitespace-pre-wrap leading-relaxed">
          {action.draft_content}
        </pre>
      </div>

      {/* Approve button */}
      {!isApproved && onApprove && (
        <div className="px-5 py-4">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-4 h-4 text-[#f59e0b] mt-0.5 shrink-0" />
            <p className="text-xs text-[#5a6380] leading-relaxed">
              This action has been generated by the AI agent and is held in
              DRAFT status. Review the content above before approving. Once
              approved, the action will be prepared for dispatch.
            </p>
          </div>
          <button
            onClick={onApprove}
            disabled={isApproving}
            className={cn(
              "mt-4 w-full py-3 px-6 rounded font-semibold text-sm tracking-wide transition-all",
              "bg-[#3b82f6] hover:bg-[#2563eb] text-white",
              "disabled:opacity-50 disabled:cursor-not-allowed",
              "focus:outline-none focus:ring-2 focus:ring-[#3b82f6] focus:ring-offset-2 focus:ring-offset-[#09090f]"
            )}
          >
            {isApproving ? "Approving…" : "Approve & Prepare"}
          </button>
        </div>
      )}
    </div>
  );
}

