"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import {
  Shield,
  LayoutDashboard,
  Upload,
  Cpu,
  FolderSearch,
  FileBarChart,
  Bell,
  Download,
  Calendar,
  ChevronDown,
  ArrowRight,
} from "lucide-react";
import { ThemeToggle } from "@/components/ThemeToggle";

interface DashboardLayoutProps {
  children: React.ReactNode;
  runId?: string;
  activeNav?: "dashboard" | "upload" | "processing" | "cases" | "reports";
  headerTitle?: string;
  headerSubtitle?: string;
}

export function DashboardLayout({
  children,
  runId = "run-2024-08-001",
  activeNav,
  headerTitle,
  headerSubtitle,
}: DashboardLayoutProps) {
  const pathname = usePathname();
  const [downloadSuccess, setDownloadSuccess] = useState(false);
  const [userName, setUserName] = useState("Ishan Vaidya");
  const [userOrg, setUserOrg] = useState("GST Compliance Lead");

  useEffect(() => {
    try {
      const stored = localStorage.getItem("user");
      if (stored) {
        const parsed = JSON.parse(stored);
        if (parsed.name) setUserName(parsed.name);
        if (parsed.organisation) setUserOrg(parsed.organisation);
      }
    } catch {}
  }, []);

  const userInitials = userName
    .split(" ")
    .map((w) => w[0])
    .join("")
    .toUpperCase()
    .substring(0, 2);

  // Determine current active nav item if not explicitly passed
  const currentActive =
    activeNav ||
    (pathname.startsWith("/cases")
      ? "cases"
      : pathname.startsWith("/audit")
      ? "processing"
      : pathname.startsWith("/upload")
      ? "upload"
      : "dashboard");

  const handleDownloadReport = () => {
    setDownloadSuccess(true);
    const content = `GST ARCHANGEL — AUDIT SUMMARY REPORT\nRun ID: ${runId}\nPeriod: Jul 1 - Jul 31, 2024\n\nStatus: COMPLETE (100% Reconciled)\nOverall Risk Score: 82/100 (HIGH RISK)\nTotal Transactions: 25\nMatched: 19 (76%)\nDiscrepancies: 6 (24%)\nTotal ITC at Risk: INR 3,12,500\n\nPriority Action: Request Missing Invoices from Vision Infotech (INR 1,25,000) and Kalyani Traders.\nGenerated by GST ARCHANGEL Autonomous Compliance Agent.`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `GST_Audit_Report_${runId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setTimeout(() => setDownloadSuccess(false), 3000);
  };

  return (
    <div className="flex min-h-screen bg-[#F4F6FB] dark:bg-[#080B14] text-[#0E1630] dark:text-[#F8FAFC] transition-colors duration-200">
      {/* ── 1. Minimal Sidebar ────────────────────────────────────────────────── */}
      <aside className="hidden lg:flex w-64 flex-col justify-between border-r border-[#E2E8F0] dark:border-[#1E293B] bg-white dark:bg-[#0D1220] p-5 shrink-0 sticky top-0 h-screen overflow-y-auto transition-colors duration-200">
        <div>
          {/* Logo */}
          <Link href="/" className="flex items-center gap-3 px-2 py-2 mb-8 group">
            <div className="flex h-9 w-9 items-center justify-center rounded-[12px] bg-gradient-to-br from-[#4F6EF7] to-[#8B5CF6] text-white shadow-md shadow-indigo-500/25 group-hover:scale-105 transition-transform">
              <Shield size={20} />
            </div>
            <div>
              <span className="font-[Manrope,sans-serif] text-[18px] font-extrabold tracking-tight">
                <span className="text-[#0E1630] dark:text-white">GST</span>{" "}
                <span className="text-[#4F6EF7] dark:text-[#60A5FA]">ARCHANGEL</span>
              </span>
              <p className="text-[10.5px] font-medium text-[#64748B] dark:text-[#94A3B8]">
                AI-Powered GST Compliance
              </p>
            </div>
          </Link>

          {/* Navigation Links */}
          <nav className="flex flex-col gap-1.5">
            <Link
              href={`/dashboard/${runId}`}
              className={`flex items-center gap-3 rounded-[14px] px-3.5 py-3 text-[14px] font-bold transition-all ${
                currentActive === "dashboard"
                  ? "bg-[#EEF2FF] dark:bg-[#1E2238] text-[#4F6EF7] dark:text-[#60A5FA] shadow-sm"
                  : "text-[#64748B] dark:text-[#94A3B8] hover:bg-[#F8FAFC] dark:hover:bg-[#151B2B] hover:text-[#0E1630] dark:hover:text-white"
              }`}
            >
              <LayoutDashboard size={18} />
              <span>Dashboard</span>
            </Link>

            <Link
              href="/upload"
              className={`flex items-center gap-3 rounded-[14px] px-3.5 py-3 text-[14px] font-semibold transition-all ${
                currentActive === "upload"
                  ? "bg-[#EEF2FF] dark:bg-[#1E2238] text-[#4F6EF7] dark:text-[#60A5FA] shadow-sm"
                  : "text-[#64748B] dark:text-[#94A3B8] hover:bg-[#F8FAFC] dark:hover:bg-[#151B2B] hover:text-[#0E1630] dark:hover:text-white"
              }`}
            >
              <Upload size={18} />
              <span>Upload Data</span>
            </Link>

            <Link
              href={`/audit/${runId}/processing`}
              className={`flex items-center gap-3 rounded-[14px] px-3.5 py-3 text-[14px] font-semibold transition-all ${
                currentActive === "processing"
                  ? "bg-[#EEF2FF] dark:bg-[#1E2238] text-[#4F6EF7] dark:text-[#60A5FA] shadow-sm"
                  : "text-[#64748B] dark:text-[#94A3B8] hover:bg-[#F8FAFC] dark:hover:bg-[#151B2B] hover:text-[#0E1630] dark:hover:text-white"
              }`}
            >
              <Cpu size={18} />
              <span>Audit Processing</span>
            </Link>

            <Link
              href="/cases"
              className={`flex items-center gap-3 rounded-[14px] px-3.5 py-3 text-[14px] font-bold transition-all ${
                currentActive === "cases"
                  ? "bg-[#EEF2FF] dark:bg-[#1E2238] text-[#4F6EF7] dark:text-[#60A5FA] shadow-sm"
                  : "text-[#64748B] dark:text-[#94A3B8] hover:bg-[#F8FAFC] dark:hover:bg-[#151B2B] hover:text-[#0E1630] dark:hover:text-white"
              }`}
            >
              <FolderSearch size={18} />
              <span>Cases</span>
            </Link>

            <button
              type="button"
              onClick={handleDownloadReport}
              className={`flex items-center gap-3 rounded-[14px] px-3.5 py-3 text-[14px] font-semibold transition-all text-left w-full cursor-pointer ${
                currentActive === "reports"
                  ? "bg-[#EEF2FF] dark:bg-[#1E2238] text-[#4F6EF7] dark:text-[#60A5FA] shadow-sm"
                  : "text-[#64748B] dark:text-[#94A3B8] hover:bg-[#F8FAFC] dark:hover:bg-[#151B2B] hover:text-[#0E1630] dark:hover:text-white"
              }`}
            >
              <FileBarChart size={18} />
              <span>Reports</span>
            </button>
          </nav>
        </div>

        {/* Current Audit Run Card at Bottom */}
        <div className="rounded-[18px] border border-[#E2E8F0] dark:border-[#1E293B] bg-[#F8FAFC] dark:bg-[#151B2B] p-4 shadow-sm transition-colors duration-200">
          <div className="flex items-center justify-between text-[11px] font-extrabold uppercase tracking-wider text-[#64748B] dark:text-[#94A3B8] mb-2">
            <span>CURRENT AUDIT RUN</span>
            <span className="flex h-2 w-2 rounded-full bg-emerald-500 animate-pulse" />
          </div>

          {/* Mini waveform svg */}
          <div className="my-2 h-7 w-full">
            <svg viewBox="0 0 100 25" className="h-full w-full stroke-[#4F6EF7] dark:stroke-[#60A5FA] fill-none">
              <path
                d="M 0 15 Q 15 5, 30 15 T 60 12 T 85 18 T 100 8"
                strokeWidth="2"
                strokeLinecap="round"
              />
            </svg>
          </div>

          <div className="flex items-center justify-between text-[12px] text-[#475569] dark:text-[#CBD5E1] mb-1">
            <span>Status</span>
            <span className="font-semibold text-emerald-600 dark:text-emerald-400 flex items-center gap-1">
              <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
              Completed
            </span>
          </div>

          <div className="flex items-center justify-between text-[12px] text-[#475569] dark:text-[#CBD5E1] mb-1">
            <span>Run ID</span>
            <span className="font-mono font-bold text-[#0E1630] dark:text-white">{runId}</span>
          </div>

          <div className="flex items-center justify-between text-[12px] text-[#475569] dark:text-[#CBD5E1] mb-3">
            <span>Period</span>
            <span className="font-medium text-[#0E1630] dark:text-white">Jul 2024</span>
          </div>

          <Link
            href={`/audit/${runId}/processing`}
            className="flex items-center justify-center gap-1.5 rounded-[12px] border border-[#E2E8F0] dark:border-[#1E293B] bg-white dark:bg-[#0D1220] py-2 text-[12px] font-bold text-[#4F6EF7] dark:text-[#60A5FA] hover:bg-indigo-50/50 dark:hover:bg-[#1E2238] shadow-sm transition-all text-center"
          >
            <span>View Audit Details</span>
            <ArrowRight size={13} />
          </Link>
        </div>
      </aside>

      {/* ── 2. Main Content Area ─────────────────────────────────────────────── */}
      <div className="flex-1 flex flex-col min-w-0 overflow-x-hidden">
        {/* Top Header */}
        <header className="sticky top-0 z-30 flex flex-wrap items-center justify-between gap-4 border-b border-[#E2E8F0] dark:border-[#1E293B] bg-white/90 dark:bg-[#0D1220]/90 px-6 py-4 backdrop-blur-md transition-colors duration-200">
          {/* Left Title / Breadcrumbs */}
          <div className="flex items-center gap-4">
            <div>
              <div className="flex items-center gap-2">
                <h1 className="font-[Manrope,sans-serif] text-[20px] font-extrabold text-[#0E1630] dark:text-white">
                  {headerTitle || "Good morning, Ishan 🖐️"}
                </h1>
                <span className="hidden sm:inline-flex items-center gap-1.5 rounded-full bg-emerald-50 dark:bg-emerald-950/50 border border-emerald-200/80 dark:border-emerald-800 px-2.5 py-0.5 text-[11.5px] font-bold text-emerald-700 dark:text-emerald-400">
                  <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" /> Audit Completed
                </span>
              </div>
              <p className="text-[13px] text-[#64748B] dark:text-[#94A3B8]">
                {headerSubtitle || "Here's your AI audit summary"}
              </p>
            </div>
          </div>

          {/* Right Controls */}
          <div className="flex items-center gap-3">
            {/* Period Selector */}
            <div className="relative inline-flex items-center gap-2 rounded-full border border-[#E2E8F0] dark:border-[#1E293B] bg-white dark:bg-[#151B2B] px-3.5 py-2 text-[13px] font-semibold text-[#404A63] dark:text-[#CBD5E1] shadow-sm transition-colors duration-200">
              <Calendar size={15} className="text-[#4F6EF7] dark:text-[#60A5FA]" />
              <span>Jul 1 - Jul 31, 2024</span>
              <ChevronDown size={14} className="text-[#94A3B8]" />
            </div>

            {/* Download Report Button */}
            <button
              type="button"
              onClick={handleDownloadReport}
              className="inline-flex items-center gap-2 rounded-full border border-[#E2E8F0] dark:border-[#1E293B] bg-white dark:bg-[#151B2B] px-4 py-2 text-[13px] font-semibold text-[#4F6EF7] dark:text-[#60A5FA] hover:border-[#4F6EF7] dark:hover:border-[#60A5FA] shadow-sm transition-all cursor-pointer"
            >
              <Download size={15} />
              <span>{downloadSuccess ? "Report Downloaded!" : "Download Report"}</span>
            </button>

            {/* Global Theme Toggle */}
            <ThemeToggle />

            {/* Notifications */}
            <div className="relative flex h-9 w-9 items-center justify-center rounded-full border border-[#E2E8F0] dark:border-[#1E293B] bg-white dark:bg-[#151B2B] text-[#64748B] dark:text-[#94A3B8] shadow-sm transition-colors duration-200">
              <Bell size={16} />
              <span className="absolute -top-1 -right-1 flex h-4 w-4 items-center justify-center rounded-full bg-rose-500 text-[10px] font-extrabold text-white">
                3
              </span>
            </div>

            {/* User Profile */}
            <div className="flex items-center gap-2.5 pl-2 border-l border-[#E2E8F0] dark:border-[#1E293B]">
              <div className="flex h-9 w-9 items-center justify-center rounded-full bg-gradient-to-br from-[#4F6EF7] to-[#8B5CF6] text-white font-bold text-[13px] shadow-sm">
                {userInitials}
              </div>
              <div className="hidden xl:block">
                <p className="text-[13px] font-bold text-[#0E1630] dark:text-white leading-none">
                  {userName}
                </p>
                <p className="text-[11px] text-[#64748B] dark:text-[#94A3B8] mt-0.5">
                  {userOrg}
                </p>
              </div>
            </div>
          </div>
        </header>

        {/* Main Content Body */}
        <main className="flex-1 p-6 max-w-[1600px] w-full mx-auto">{children}</main>
      </div>
    </div>
  );
}
